#!/usr/bin/env python
from os import path
from tuf.repository_tool import *

master_dir = 'repo-master'
keys_dir = path.join(master_dir, 'keys')
root_key_file = path.join(keys_dir, 'root_key')

# Create root keys
generate_and_write_rsa_keypair(root_key_file)

