#!/usr/bin/env python
from os import path
from tuf.repository_tool import *

master_dir = 'repo-master'
keys_dir = path.join(master_dir, 'keys')
root_key_file = path.join(keys_dir, 'root_key')
repo_dir = path.join(master_dir, 'repository')

# Import root keys
public_root_key = import_rsa_publickey_from_file(root_key_file + '.pub')
private_root_key = import_rsa_privatekey_from_file(root_key_file)

